//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountClickKey.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountClickKey.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What does the program do?.
        /// </summary>
        internal static string m_Ask1 {
            get {
                return ResourceManager.GetString("m_Ask1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When statistics are reset to zero?.
        /// </summary>
        internal static string m_Ask2 {
            get {
                return ResourceManager.GetString("m_Ask2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Keys.
        /// </summary>
        internal static string m_ButtonAllKeys_Type {
            get {
                return ResourceManager.GetString("m_ButtonAllKeys_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Time.
        /// </summary>
        internal static string m_ButtonAllTime_Period {
            get {
                return ResourceManager.GetString("m_ButtonAllTime_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string m_ButtonDay_Period {
            get {
                return ResourceManager.GetString("m_ButtonDay_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Block.
        /// </summary>
        internal static string m_ButtonFunctionalBlock_Type {
            get {
                return ResourceManager.GetString("m_ButtonFunctionalBlock_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string m_ButtonHome {
            get {
                return ResourceManager.GetString("m_ButtonHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string m_ButtonMonth_Period {
            get {
                return ResourceManager.GetString("m_ButtonMonth_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Keypad.
        /// </summary>
        internal static string m_ButtonNumericKeypad_Type {
            get {
                return ResourceManager.GetString("m_ButtonNumericKeypad_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string m_ButtonSettings {
            get {
                return ResourceManager.GetString("m_ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        internal static string m_ButtonStats {
            get {
                return ResourceManager.GetString("m_ButtonStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string m_ButtonSupport {
            get {
                return ResourceManager.GetString("m_ButtonSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string m_ButtonWeek_Period {
            get {
                return ResourceManager.GetString("m_ButtonWeek_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writer Keys.
        /// </summary>
        internal static string m_ButtonWriterKeys_Type {
            get {
                return ResourceManager.GetString("m_ButtonWriterKeys_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string m_ButtonYear_Period {
            get {
                return ResourceManager.GetString("m_ButtonYear_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicked.
        /// </summary>
        internal static string m_Clicked {
            get {
                return ResourceManager.GetString("m_Clicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for the year are reset every new year..
        /// </summary>
        internal static string m_FifthAnswerToSecondAsk {
            get {
                return ResourceManager.GetString("m_FifthAnswerToSecondAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is designed for:.
        /// </summary>
        internal static string m_FirstAnswerToFirstAsk {
            get {
                return ResourceManager.GetString("m_FirstAnswerToFirstAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics are reset when the application is launched..
        /// </summary>
        internal static string m_FirstAnswerToSecondAsk {
            get {
                return ResourceManager.GetString("m_FirstAnswerToSecondAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for the month are reset every new month..
        /// </summary>
        internal static string m_FourthAnswerToSecondAsk {
            get {
                return ResourceManager.GetString("m_FourthAnswerToSecondAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string m_Language {
            get {
                return ResourceManager.GetString("m_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Collecting keystrokes on the keyboard.
        /// </summary>
        internal static string m_SecondAnswerToFirstAsk {
            get {
                return ResourceManager.GetString("m_SecondAnswerToFirstAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics for the day are reset when the next day comes..
        /// </summary>
        internal static string m_SecondAnswerToSecondAsk {
            get {
                return ResourceManager.GetString("m_SecondAnswerToSecondAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string m_Settings {
            get {
                return ResourceManager.GetString("m_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string m_Support {
            get {
                return ResourceManager.GetString("m_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string m_Theme {
            get {
                return ResourceManager.GetString("m_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Output statistics of keystrokes by time period and key type.
        /// </summary>
        internal static string m_ThirdAnswerToFirstAsk {
            get {
                return ResourceManager.GetString("m_ThirdAnswerToFirstAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The statistics for the week are reset on Monday..
        /// </summary>
        internal static string m_ThirdAnswerToSecondAsk {
            get {
                return ResourceManager.GetString("m_ThirdAnswerToSecondAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string m_Version {
            get {
                return ResourceManager.GetString("m_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
    }
}
